// import "@/styles/globals.css";

// import { Inter } from "next/font/google";
// import { headers } from "next/headers";

// import { TRPCReactProvider } from "@/trpc/react";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`font-sans ${inter.variable}`}>
//         <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
//       </body>
//     </html>
//   );
// }


// react
import type { ReactNode } from 'react'
// styles
import './_styles/globals.css'
// components
import Test from '../components/Test'
import { Analytics } from '@vercel/analytics/react'


export default function RootLayout(props: {
    children: ReactNode
    modal: ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Test />

                {props.modal}
                {props.children}

                <Analytics />
            </body>
        </html>
    )
}
